"""add profile fields

Revision ID: 7a4f52690f1a
Revises: 99b58768e2e9
Create Date: 2026-04-28 16:05:17.337725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '7a4f52690f1a'
down_revision: Union[str, None] = '99b58768e2e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('birth_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('university', sa.String(), nullable=True))
    op.add_column('users', sa.Column('profile_picture_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_picture_url')
    op.drop_column('users', 'university')
    op.drop_column('users', 'birth_date')
    # ### end Alembic commands ###
