"""add focus and submission

Revision ID: 99b58768e2e9
Revises: f8dea5a791a3
Create Date: 2026-04-27 13:41:11.534284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '99b58768e2e9'
down_revision: Union[str, None] = 'f8dea5a791a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("COMMIT")
    op.execute("ALTER TYPE eventtype ADD VALUE IF NOT EXISTS 'FOCUS'")
    op.add_column('tasks', sa.Column('is_submission', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'is_submission')
    # ### end Alembic commands ###
