"""Add semester_tag, event_date, lecturer to events

Revision ID: f8dea5a791a3
Revises: 5c2e26a564f2
Create Date: 2026-04-20 21:27:23.073633

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'f8dea5a791a3'
down_revision: Union[str, None] = '5c2e26a564f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('semester_tag', sa.String(length=50), nullable=True))
    op.add_column('events', sa.Column('event_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('events', sa.Column('lecturer', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###
    
    op.execute("ALTER TYPE eventtype ADD VALUE IF NOT EXISTS 'EXERCISE'")
    op.execute("ALTER TYPE eventtype ADD VALUE IF NOT EXISTS 'TUTORIAL'")
    op.execute("ALTER TYPE eventtype ADD VALUE IF NOT EXISTS 'SEMINAR'")
    op.execute("ALTER TYPE eventtype ADD VALUE IF NOT EXISTS 'PRACTICUM'")
    op.execute("ALTER TYPE eventtype ADD VALUE IF NOT EXISTS 'WORK'")
    op.execute("ALTER TYPE eventtype ADD VALUE IF NOT EXISTS 'LIFE'")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'lecturer')
    op.drop_column('events', 'event_date')
    op.drop_column('events', 'semester_tag')
    # ### end Alembic commands ###
