"""add email verification fields to user

Revision ID: 18076c42fc0d
Revises: 0003
Create Date: 2026-04-20 14:00:09.628842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '18076c42fc0d'
down_revision: Union[str, None] = '0003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_verified', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('users', sa.Column('verification_code', sa.String(), nullable=True))
    op.add_column('users', sa.Column('verification_expires_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'verification_expires_at')
    op.drop_column('users', 'verification_code')
    op.drop_column('users', 'is_verified')
    # ### end Alembic commands ###
