"""add matrikelnummer

Revision ID: c9067df2827c
Revises: 18076c42fc0d
Create Date: 2026-04-20 16:45:54.540045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'c9067df2827c'
down_revision: Union[str, None] = '18076c42fc0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('matrikelnummer', sa.String(), nullable=True))
    op.create_index(op.f('ix_users_matrikelnummer'), 'users', ['matrikelnummer'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_matrikelnummer'), table_name='users')
    op.drop_column('users', 'matrikelnummer')
    # ### end Alembic commands ###
